//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ForecastCell`.
    static let forecastCell: Rswift.ReuseIdentifier<ForecastWeatherTableViewCell> = Rswift.ReuseIdentifier(identifier: "ForecastCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `CurrentWeather`.
    static let currentWeather = _R.storyboard.currentWeather()
    /// Storyboard `ForecastWeather`.
    static let forecastWeather = _R.storyboard.forecastWeather()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "CurrentWeather", bundle: ...)`
    static func currentWeather(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.currentWeather)
    }
    
    /// `UIStoryboard(name: "ForecastWeather", bundle: ...)`
    static func forecastWeather(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.forecastWeather)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try currentWeather.validate()
      try forecastWeather.validate()
      try launchScreen.validate()
    }
    
    struct currentWeather: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "CurrentWeather"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct forecastWeather: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let forecastWeather = StoryboardViewControllerResource<WeatherApp.ForecastWeatherTableViewController>(identifier: "ForecastWeather")
      let name = "ForecastWeather"
      
      func forecastWeather(_: Void = ()) -> WeatherApp.ForecastWeatherTableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: forecastWeather)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.forecastWeather().forecastWeather() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'forecastWeather' could not be loaded from storyboard 'ForecastWeather' as 'WeatherApp.ForecastWeatherTableViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
